yarnPath: ".yarn/releases/yarn-berry.js"
nodeLinker: pnp
packageExtensions:
  "@gitbeaker/browser@*":
    dependencies:
      "form-data": "*"
  "@nivo/legends@*":
    dependencies:
      "@nivo/colors": "*"
      "d3-scale": "*"
