yarnPath: ".yarn/releases/yarn-berry.js"
nodeLinker: pnp
# If set to hardlinks-local Yarn will utilize hardlinks to reduce disk space consumption inside node_modules directories in a current project. With hardlinks-global Yarn will use global content addressable storage to reduce node_modules size across all the projects using this option.
# https://yarnpkg.com/configuration/yarnrc#nmMode
nmMode: hardlinks-global
# If true, Yarn will disregard the cacheFolder settings and will store the cache files into a folder shared by all local projects sharing the same configuration.
enableGlobalCache: true
compressionLevel: 0
packageExtensions:
  "@gitbeaker/browser@*":
    dependencies:
      "form-data": "*"
  "@nivo/legends@*":
    dependencies:
      "@nivo/colors": "*"
      "d3-scale": "*"
